name: Docker Image Builder

on:
  release:
    types: [ released ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven Build
        run: mvn clean install
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Infer Docker image tag
        id: docker_image_tag_inferring_step
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker_image_tag=$(echo $RELEASE_TAG | cut -d'v' -f 2)
          echo "::set-output name=docker_image_tag::$docker_image_tag"
        
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: gayashanbc/my-tomcat:latest, gayashanbc/my-tomcat:${{ steps.docker_image_tag_inferring_step.outputs.docker_image_tag }}
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
